# -*- coding: utf-8 -*-
"""Final Python Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D9TkEafl8z8GwxgC97JVLeVcwcz-u_58
"""

!pip install pymysql sqlalchemy pandas matplotlib seaborn

from google.colab import files
uploaded = files.upload()

import pandas as pd

df_orders = pd.read_csv("Oders.csv")
df_order_items = pd.read_csv("Order_items.csv")
df_customers = pd.read_csv("Customers.csv")

print("Orders:", df_orders.shape)
print("Order Items:", df_order_items.shape)
print("Customers:", df_customers.shape)

import pandas as pd
import datetime
from google.colab import files

uploaded = files.upload()

# Load CSV files
df_orders = pd.read_csv("Oders.csv")
df_order_items = pd.read_csv("Order_items.csv")
df_customers = pd.read_csv("Customers.csv")

# Line total calculate
df_order_items['line_total'] = (
    df_order_items['quantity'] *
    df_order_items['list_price'] *
    (1 - df_order_items['discount'])
)

# order_date convert
df_orders['order_date'] = pd.to_datetime(df_orders['order_date'])

# Merge
df_merged = df_orders.merge(df_order_items, on='order_id')

# Reference date
ref_date = df_orders['order_date'].max() + datetime.timedelta(days=1)

# RFM
rfm = df_merged.groupby('customer_id').agg(
    Recency=('order_date', lambda x: (ref_date - x.max()).days),
    Frequency=('order_id', 'nunique'),
    Monetary=('line_total', 'sum')
).reset_index()

# Scoring
rfm['R_Score'] = pd.qcut(rfm['Recency'], 5, labels=[5,4,3,2,1])
rfm['F_Score'] = pd.qcut(rfm['Frequency'].rank(method='first'), 5, labels=[1,2,3,4,5])
rfm['M_Score'] = pd.qcut(rfm['Monetary'], 5, labels=[1,2,3,4,5])
rfm['RFM_Score'] = rfm['R_Score'].astype(int) + rfm['F_Score'].astype(int) + rfm['M_Score'].astype(int)

# Segment Label
def segment_label(score):
    if score >= 12:
        return 'High'
    elif score >= 7:
        return 'Medium'
    else:
        return 'Low'

rfm['segment_label'] = rfm['RFM_Score'].apply(segment_label)

# df_to_sql prepare
df_to_sql = rfm[['customer_id', 'segment_label', 'RFM_Score']].copy()
df_to_sql.columns = ['customer_id', 'segment_label', 'segment_score']
df_to_sql['model_version'] = 'v1.0'


print(df_to_sql.head())

# Export CSV
df_to_sql.to_csv("customer_segments.csv", index=False)
files.download("customer_segments.csv")

# Basic EDA
# Cell 1 — Info & Describe:
# Orders
print("=== ORDERS ===")
print(df_orders.info())
print(df_orders.describe())

# Order Items
print("=== ORDER ITEMS ===")
print(df_order_items.info())
print(df_order_items.describe())

# Customers
print("=== CUSTOMERS ===")
print(df_customers.info())
print(df_customers.describe())

#Value Counts:
print("Orders per Store:")
print(df_orders['store_id'].value_counts())

print("\nOrders per Status:")
print(df_orders['order_status'].value_counts())

print("\nCustomers per City:")
print(df_customers['city'].value_counts())

#Charts:
import matplotlib.pyplot as plt
import seaborn as sns

# Chart 1: Orders per Store
plt.figure(figsize=(8,5))
sns.countplot(x='store_id', data=df_orders)
plt.title("Orders per Store")
plt.xlabel("Store ID")
plt.ylabel("Order Count")
plt.show()

# Chart 2: Top 10 Products by Quantity
top_products = df_order_items.groupby('product_id')['quantity'].sum().sort_values(ascending=False).head(10)
plt.figure(figsize=(10,5))
top_products.plot(kind='bar', color='steelblue')
plt.title("Top 10 Products by Quantity Sold")
plt.xlabel("Product ID")
plt.ylabel("Quantity")
plt.show()

# Chart 3: Revenue Distribution
df_order_items['line_total'] = df_order_items['quantity'] * df_order_items['list_price'] * (1 - df_order_items['discount'])
plt.figure(figsize=(8,5))
sns.histplot(df_order_items['line_total'], bins=30, kde=True, color='green')
plt.title("Revenue Distribution per Order Item")
plt.xlabel("Line Total")
plt.show()

#RFM Features
# — Merge & Prepare:
import datetime

# Line total calculate
df_order_items['line_total'] = (
    df_order_items['quantity'] *
    df_order_items['list_price'] *
    (1 - df_order_items['discount'])
)

# order_date convert
df_orders['order_date'] = pd.to_datetime(df_orders['order_date'])

# Merge orders + order_items
df_merged = df_orders.merge(df_order_items, on='order_id')

print( df_merged.shape)

# Reference date
ref_date = df_orders['order_date'].max() + datetime.timedelta(days=1)

# RFM
rfm = df_merged.groupby('customer_id').agg(
    Recency=('order_date', lambda x: (ref_date - x.max()).days),
    Frequency=('order_id', 'nunique'),
    Monetary=('line_total', 'sum')
).reset_index()


print(rfm.head())

# Scoring
rfm['R_Score'] = pd.qcut(rfm['Recency'], 5, labels=[5,4,3,2,1])
rfm['F_Score'] = pd.qcut(rfm['Frequency'].rank(method='first'), 5, labels=[1,2,3,4,5])
rfm['M_Score'] = pd.qcut(rfm['Monetary'], 5, labels=[1,2,3,4,5])
rfm['RFM_Score'] = rfm['R_Score'].astype(int) + rfm['F_Score'].astype(int) + rfm['M_Score'].astype(int)

# Segment Label
def segment_label(score):
    if score >= 12:
        return 'High'
    elif score >= 7:
        return 'Medium'
    else:
        return 'Low'

rfm['segment_label'] = rfm['RFM_Score'].apply(segment_label)

print(rfm['segment_label'].value_counts())
print(rfm.head())

plt.figure(figsize=(6,4))
sns.countplot(x='segment_label', data=rfm, palette='Set2', order=['High','Medium','Low'])
plt.title("Customer Segments")
plt.xlabel("Segment")
plt.ylabel("Count")
plt.show()

#: Export to SQL
#Prepare & Export:
from google.colab import files

# df_to_sql prepare
df_to_sql = rfm[['customer_id', 'segment_label', 'RFM_Score']].copy()
df_to_sql.columns = ['customer_id', 'segment_label', 'segment_score']
df_to_sql['model_version'] = 'v1.0'

print(df_to_sql.head())

# Download CSV:
df_to_sql.to_csv("customer_segments.csv", index=False)
files.download("customer_segments.csv")
print("✅ Downloaded!")

